tap 'caskroom/cask'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'puma/puma'
tap 'thoughtbot/formulae'

brew 'ffmpeg'
brew 'gifsicle'
brew 'git'
brew 'go'
brew 'heroku'
brew 'jq'
brew 'libxml2'
brew 'mtr'
brew 'openssl'
brew 'postgresql'
brew 'rbenv'
brew 'redis'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'wget'
brew 'yarn'
brew 'zsh'

brew 'puma/puma/puma-dev'
brew 'thoughtbot/formulae/rcm'

cask '1password'
cask 'dropbox'
cask 'google-chrome'
cask 'docker'
cask 'slack'
cask 'zoomus'
