tap 'heroku/brew'
tap 'homebrew/services'
tap 'puma/puma'
tap 'teamookla/speedtest'

brew 'ffmpeg'
brew 'gifsicle'
brew 'git'
brew 'go'
brew 'heroku'
brew 'jq'
brew 'libxml2'
brew 'mtr'
brew 'openssl'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'rbenv'
brew 'redis'
brew 'ruby-build'
brew 'speedtest'
brew 'the_silver_searcher'
brew 'rcm'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'svn'

cask '1password'
cask 'dropbox'
cask 'google-chrome'
cask 'ngrok'
cask 'postico'
cask 'gitx'
cask 'slack'
cask 'zoom'

cask 'font-source-code-pro'
