#!/bin/sh

previous=$1         # The ref of the previous HEAD
current=$2          # The ref of the new HEAD (which may or may not have changed)
branch_checkout=$3  # A flag indicating whether the checkout was a branch checkout

trigger_bundler() {
  [ -f Gemfile ] && [ "$(git diff --name-only $previous -- Gemfile Gemfile.lock)" ]
}

trigger_migrations() {
  [ -f "db/schema.rb" ] && [ "$(git diff --diff-filter=A --name-only $previous -- db/migrate db/versions)" ]
}

trigger_yarn() {
  [ -f package.json ] && [ "$(git diff --name-only $previous -- package.json yarn.lock)" ]
}

summarize_updates() {
  if trigger_bundler || trigger_migrations || trigger_yarn ; then
    echo ""
    echo "→ Don't forget to run rup or bin/update"
    echo ""
  fi
}

if [ $branch_checkout == 1 ];  then
  summarize_updates
fi
