#!/bin/sh

previous=$1         # The ref of the previous HEAD
current=$2          # The ref of the new HEAD (which may or may not have changed)
branch_checkout=$3  # A flag indicating whether the checkout was a branch checkout

trigger_migrations() {
  [ -f "db/schema.rb" ] && [ "$(git diff --diff-filter=A --name-only $previous db/migrate)" ]
}

trigger_bundler() {
  [ -f Gemfile ] && [ "$(git diff --name-only $previous Gemfile)" ]
}

if [ $branch_checkout == 1 ]
then
  if trigger_bundler
  then
    echo "Bundling..."
    bundle install > /dev/null
  fi

  if trigger_migrations
  then
    echo "Running Migrations..."
    bin/rake db:migrate > /dev/null
  fi
fi

.git/hooks/ctags >/dev/null 2>&1 &

